"""moves model updated

Revision ID: 1a640c21d2da
Revises: d4fa3c88f984
Create Date: 2023-07-06 09:46:31.543552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a640c21d2da'
down_revision = 'd4fa3c88f984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('command', sa.String(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_moves_character_id_characters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moves'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    # ### end Alembic commands ###
