"""tables updated

Revision ID: 2aadc2ae3dfc
Revises: c3b316cf11aa
Create Date: 2023-07-11 13:54:09.299874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aadc2ae3dfc'
down_revision = 'c3b316cf11aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_characters', schema=None) as batch_op:
        batch_op.create_unique_constraint('_user_character_uc', ['user_id', 'character_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_characters', schema=None) as batch_op:
        batch_op.drop_constraint('_user_character_uc', type_='unique')

    # ### end Alembic commands ###
