"""added combos table

Revision ID: 8c1ecc1f5407
Revises: efad52fe5e6c
Create Date: 2023-07-18 11:12:28.787344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1ecc1f5407'
down_revision = 'efad52fe5e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('notation', sa.String(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_combos_character_id_characters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_combos'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combos')
    # ### end Alembic commands ###
