"""tables updated

Revision ID: c3b316cf11aa
Revises: 3c1ee75f6564
Create Date: 2023-07-11 10:28:37.453933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b316cf11aa'
down_revision = '3c1ee75f6564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_character_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_videos_user_character_id_user_characters'), 'user_characters', ['user_character_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_videos_user_character_id_user_characters'), type_='foreignkey')
        batch_op.drop_column('user_character_id')

    # ### end Alembic commands ###
