"""empty message

Revision ID: d4fa3c88f984
Revises: 
Create Date: 2023-07-05 14:30:16.151008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4fa3c88f984'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('head_img', sa.String(), nullable=True),
    sa.Column('main_img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_characters'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
