"""added training notes table

Revision ID: dc33c5797244
Revises: 2aadc2ae3dfc
Create Date: 2023-07-12 10:27:52.046594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc33c5797244'
down_revision = '2aadc2ae3dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_character_id'], ['user_characters.id'], name=op.f('fk_training_notes_user_character_id_user_characters')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_training_notes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_notes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_notes')
    # ### end Alembic commands ###
