"""added matchups table

Revision ID: efad52fe5e6c
Revises: 3902cb918f59
Create Date: 2023-07-17 13:59:41.521241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efad52fe5e6c'
down_revision = '3902cb918f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_character_id'], ['user_characters.id'], name=op.f('fk_matchups_user_character_id_user_characters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matchups'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matchups')
    # ### end Alembic commands ###
